server {
    listen 80;
    server_name localhost;
    root /app/public;
    index index.php index.html;
    absolute_redirect off;
    client_max_body_size 100M;

    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
        access_log off;
    }

    location ~ /\. {
        deny all;
    }

    location /typo3 {
        try_files $uri $uri/ /typo3/index.php?$query_string;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
